### ISSUE TITLE
Performance testing - my opinion

### ISSUE THREAD

**Issue by iwis** [coding-flamingo/BlazorComponents#3]
I think that 3 types of tests can be performed:
 1.  How long a user has to wait to see the page **for the first time**. To test it we need to clear cache by both:
     - Developer tools (F12) > Network - and check the "Disable cache" checkbox,
     - Developer tools (F12) > Application > Cache > Cache Storage - and select the "Delete" command available after clicking the right mouse button.
 2. How long a user has to wait to see the page **again by typing its address in the web browser, and pressing enter**. To test it I don't clear any cache, just press F5.
 3. How long a user has to wait to see the page **by clicking on the link to it in the application menu**.
    I don't clear any cache, I don't press F5, I only go to this page by clicking on the link to it in the application menu.

There will be a significant difference between the values of tests 1 and 2, and 2 and 3. I think the following values are acceptable for an average computer and smartphone:
- test 1: 5 seconds
- test 2: 1 second
- test 3: 0.1 seconds

Test 1 will be longer than for JavaScript applications, because **Blazor applications are bigger**, so we need to download more. In my opinion, waiting for 5 seconds is acceptable now, because:
- A user needs to wait only one time for it. The next time the DLL libraries will be already in the "Cache Storage", and the most of them can be shared by all web applications using Blazor.
- The bigger problem is with test 3.

Unfortunately, currently test 3 can be long, because **Blazor applications are much slower** than JavaScript applications. This is the most problematic in my opinion, because a user needs to wait this amount of time every time he/she clicks a link on the Blazor web site. AOT, [which is declared to be in .NET 6](https://www.reddit.com/r/Blazor/comments/mn2g3z/new_blazor_features_in_net_6_preview_3/gty3jk8/?utm_source=share&utm_medium=web2x&context=3), is supposed to help make Test 3 faster.

Disclaimer: I haven't written any Blazor app yet.

**Comment by iwis** [comment]
As I said in https://github.com/coding-flamingo/BlazorComponents/issues/2 I don't know if you cleared both caches in the "test 1".

**Comment by iwis** [comment]
I would also like to add why I think the test 3 run on a local server should be very fast (100 ms). It is because if we put the application on a server in the Internet, a user will additionally have to wait to download some JSON, photos, etc. So he/she shouldn't be additionally slowed down by a slow application. Besides, we can imagine pages more complex than just a table with 25 rows, which should also run quickly.

**Comment by igalfsg** [comment]
as mentioned in issue 2 both caches were cleared. For the testing I agree with your 3 scenarios, for this test I only cover the first one, because that is the one that blazor gets criticized for. I do believe that AOT will solve many of those problems but with the current state of things, this might be a deal breaker for someone that might be thinking of using these components. 

With these types of tests, there is a huge margin of error for things that are beyond our control, such as browser used, OS task allocation, hardware of the device, etc. I actually am usually against these types of tests because of that (I did try to minimize variability by no having any background programs or anything extra running), so the point of the videos was to show the components that have large differences, for example if Syncfusion takes 4 seconds to load while MudBlazor takes 1 second, it helps you make a decision. but a difference of 1 second of MudBlazor vs .99 second of Blazorise, could be many factors and honestly shouldn't make a difference on what framework you chose since you can't force all your clients to have the exact same setup as you.
